source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'jekyll', '~>4.2.1'

group :jekyll_plugins do
    gem "jekyll-menus"
    gem "jekyll-paginate-v2"
    gem "jekyll-paginate"
end

gem "webrick"
